### ISSUE TITLE
Flamecord error

### ISSUE THREAD

**Issue by DeltaX86** [Abdelaziz1586/PebbleAntiVPN#1]
Hello,
I ahave this error :

[19:13:43 ERROR]: Exception in thread "main" java.lang.NoClassDefFoundError: net/md_5/bungee/log/ConciseFormatter
[19:13:43 ERROR]:       at pebbleantivpn.pebbleantivpn.PebbleAntiVPNLoggerBungee.lambda$registerFilter$0(PebbleAntiVPNLoggerBungee.java:18)
[19:13:43 ERROR]:       at java.logging/java.util.logging.Logger.log(Logger.java:965)
[19:13:43 ERROR]:       at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
[19:13:43 ERROR]:       at java.logging/java.util.logging.Logger.log(Logger.java:1117)
[19:13:43 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:365)
[19:13:43 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320)
[19:13:43 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54)
[19:13:43 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Thanks

**Comment by Abdelaziz1586** [comment]
I'm so sorry for the late reply, it should be fixed in the latest version.
